In [1]:
#Andrew Weis
#Data Skills Assignment 7
#10 December 2019

import pandas as pd
import numpy as np
import bokeh
import matplotlib.pyplot as plt
from bokeh.plotting import figure, show
from bokeh.layouts import gridplot
from ipywidgets import interact, interact_manual

In [2]:
from bokeh.io import output_notebook
output_notebook()

# Start with Assignment 6 code

In [3]:
PATH='/Users/andrewweis/Documents/GitHub/DataSkills/'
FOLDER='assignment-6-awastro55/'

In [4]:
#Copied this function in part from assignment 1
def read_df(files):
    dfs=[]
    for f in files:
        df=pd.read_csv(PATH+FOLDER+f)
        dfs.append(df)
        
    return dfs

In [5]:
#Copied this function from assignment 5.  
def csv_gen(sets,base):
    return base.format(sets)

In [6]:
#Find data types
#Copied this function from assignment 5.  
def check(df):
    return df.dtypes

In [7]:
#Modeled this on similar code from assignment 5.  
csvbase='EducationDataPortal_12.02.2019_{}.csv'
datasets=['datadictionary','institutions','level_of_study','type_of_freshman']
csvlist=[csv_gen(item, csvbase) for item in datasets]
csvlist

['EducationDataPortal_12.02.2019_datadictionary.csv',
 'EducationDataPortal_12.02.2019_institutions.csv',
 'EducationDataPortal_12.02.2019_level_of_study.csv',
 'EducationDataPortal_12.02.2019_type_of_freshman.csv']

In [8]:
education=read_df(csvlist)
education #Gets 4 data frames.

[                 variable                                       label  \
 0                  unitid                              Unit ID number
 1          number_applied                        Number of applicants
 2         number_admitted                        Number of admissions
 3   sat_crit_read_25_pctl  SAT critical reading 25th percentile score
 4   sat_crit_read_75_pctl  SAT critical reading 75th percentile score
 5        sat_math_25_pctl              SAT math 25th percentile score
 6        sat_math_75_pctl              SAT math 75th percentile score
 7   act_composite_25_pctl         ACT composite 25th percentile score
 8   act_composite_75_pctl         ACT composite 75th percentile score
 9     act_english_25_pctl           ACT english 25th percentile score
 10    act_english_75_pctl           ACT english 75th percentile score
 11       act_math_25_pctl              ACT math 25th percentile score
 12       act_math_75_pctl              ACT math 75th percentile score
 13              inst_name                   Institution (entity) name
 14           inst_control                      Control of institution
 15      institution_level                        Level of institution
 16         level_of_study                              Level of study
 17        enrollment_fall                             Fall enrollment
 18     state_of_residence                          State of residence
 19       type_of_freshman                            Type of freshman

                                           description  \
 0   Unique identification number of the institutio...
 1   The number of first-time, degree/certificate-s...
 2   The number of first-time, degree/certificate-s...
 3                                                None
 4                                                None
 5                                                None
 6                                                None
 7                                                None
 8                                                None
 9                                                None
 10                                               None
 11                                               None
 12                                               None
 13                                               None
 14                                               None
 15                                               None
 16  An undergraduate student is one enrolled in a ...
 17  Enrollment reported is of the institution's of...
 18                                               None
 19                                               None

                                             source  source2
 0   Integrated Postsecondary Education Data System      NaN
 1   Integrated Postsecondary Education Data System      NaN
 2   Integrated Postsecondary Education Data System      NaN
 3   Integrated Postsecondary Education Data System      NaN
 4   Integrated Postsecondary Education Data System      NaN
 5   Integrated Postsecondary Education Data System      NaN
 6   Integrated Postsecondary Education Data System      NaN
 7   Integrated Postsecondary Education Data System      NaN
 8   Integrated Postsecondary Education Data System      NaN
 9   Integrated Postsecondary Education Data System      NaN
 10  Integrated Postsecondary Education Data System      NaN
 11  Integrated Postsecondary Education Data System      NaN
 12  Integrated Postsecondary Education Data System      NaN
 13  Integrated Postsecondary Education Data System      NaN
 14  Integrated Postsecondary Education Data System      NaN
 15  Integrated Postsecondary Education Data System      NaN
 16  Integrated Postsecondary Education Data System      NaN
 17  Integrated Postsecondary Education Data System      NaN
 18  Integrated Postsecondary Education Data System      NaN
 19  Integrated Postsecondary Education Data System      NaN  ,
      year  unitid                                          inst_name  \
 0    2016  160959                            College of the Atlantic
 1    2016  160977                                      Bates College
 2    2016  161004                                    Bowdoin College
 3    2016  161086                                      Colby College
 4    2016  161217                     University of Maine at Augusta
 5    2016  161226                  University of Maine at Farmington
 6    2016  161235                   University of Maine at Fort Kent
 7    2016  161244                     University of Maine at Machias
 8    2016  161253                                University of Maine
 9    2016  161280          University of Maine-System Central Office
 10   2016  161299                             Maine Maritime Academy
 11   2016  161341                University of Maine at Presque Isle
 12   2016  161457                          University of New England
 13   2016  161509                               Maine College of Art
 14   2016  161518                    Saint Joseph's College of Maine
 15   2016  161554                       University of Southern Maine
 16   2016  161563                                     Thomas College
 17   2016  161572                                      Unity College
 18   2016  462044  Institute for Doctoral Studies in the Visual Arts
 19   2016  487524                                  Husson University
 20   2015  160959                            College of the Atlantic
 21   2015  160977                                      Bates College
 22   2015  161004                                    Bowdoin College
 23   2015  161086                                      Colby College
 24   2015  161165                                  Husson University
 25   2015  161217                     University of Maine at Augusta
 26   2015  161226                  University of Maine at Farmington
 27   2015  161235                   University of Maine at Fort Kent
 28   2015  161244                     University of Maine at Machias
 29   2015  161253                                University of Maine
 ..    ...     ...                                                ...
 318  2002  161518                              SAINT JOSEPHS COLLEGE
 319  2002  161554                       UNIVERSITY OF SOUTHERN MAINE
 320  2002  161563                                     THOMAS COLLEGE
 321  2002  161572                                      UNITY COLLEGE
 322  2002  373827               NEW ENGLAND SCHOOL OF COMMUNICATIONS
 323  2002  407230                        BANGOR THEOLOGICAL SEMINARY
 324  2001  160959                            COLLEGE OF THE ATLANTIC
 325  2001  160968                        BANGOR THEOLOGICAL SEMINARY
 326  2001  160977                                      BATES COLLEGE
 327  2001  161004                                    BOWDOIN COLLEGE
 328  2001  161086                                      COLBY COLLEGE
 329  2001  161147                           FAITH SCHOOL OF THEOLOGY
 330  2001  161165                                     HUSSON COLLEGE
 331  2001  161217                     UNIVERSITY OF MAINE AT AUGUSTA
 332  2001  161226                  UNIVERSITY OF MAINE AT FARMINGTON
 333  2001  161235                   UNIVERSITY OF MAINE AT FORT KENT
 334  2001  161244                     UNIVERSITY OF MAINE AT MACHIAS
 335  2001  161253                                UNIVERSITY OF MAINE
 336  2001  161280          UNIVERSITY OF MAINE SYSTEM CENTRAL OFFICE
 337  2001  161299                             MAINE MARITIME ACADEMY
 338  2001  161341                UNIVERSITY OF MAINE AT PRESQUE ISLE
 339  2001  161448                  NEW ENGLAND BAPTIST BIBLE COLLEGE
 340  2001  161457        UNIVERSITY OF NEW ENGLAND-UNIVERSITY CAMPUS
 341  2001  161509                               MAINE COLLEGE OF ART
 342  2001  161518                              SAINT JOSEPHS COLLEGE
 343  2001  161554                       UNIVERSITY OF SOUTHERN MAINE
 344  2001  161563                                     THOMAS COLLEGE
 345  2001  161572                                      UNITY COLLEGE
 346  2001  373827               NEW ENGLAND SCHOOL OF COMMUNICATIONS
 347  2001  407230                        BANGOR THEOLOGICAL SEMINARY

     state_name  number_applied  number_admitted  sat_crit_read_25_pctl  \
 0        Maine           485.0            314.0                    NaN
 1        Maine          5356.0           1213.0                    NaN
 2        Maine          6799.0           1009.0                    NaN
 3        Maine          9833.0           1840.0                  630.0
 4        Maine             NaN              NaN                    NaN
 5        Maine          1880.0           1512.0                    NaN
 6        Maine           481.0            392.0                  390.0
 7        Maine             NaN              NaN                    NaN
 8        Maine         12952.0          11625.0                  470.0
 9        Maine             NaN              NaN                    NaN
 10       Maine           882.0            666.0                  450.0
 11       Maine          1491.0           1293.0                    NaN
 12       Maine          4883.0           4056.0                  470.0
 13       Maine           529.0            457.0                    NaN
 14       Maine          1323.0           1033.0                  420.0
 15       Maine          4111.0           3299.0                  440.0
 16       Maine             NaN              NaN                    NaN
 17       Maine           991.0            920.0                    NaN
 18       Maine             NaN              NaN                    NaN
 19       Maine          2460.0           1974.0                  430.0
 20       Maine           400.0            302.0                    NaN
 21       Maine          5651.0           1231.0                    NaN
 22       Maine          6790.0           1010.0                    NaN
 23       Maine          7593.0           1710.0                  630.0
 24       Maine             NaN              NaN                    NaN
 25       Maine             NaN              NaN                    NaN
 26       Maine          1614.0           1346.0                    NaN
 27       Maine           215.0            192.0                  400.0
 28       Maine             NaN              NaN                    NaN
 29       Maine         11044.0          10073.0                  480.0
 ..         ...             ...              ...                    ...
 318      Maine          1129.0            925.0                  420.0
 319      Maine          3664.0           2741.0                  450.0
 320      Maine           487.0            393.0                  400.0
 321      Maine           625.0            502.0                    NaN
 322      Maine           240.0            159.0                    NaN
 323      Maine             NaN              NaN                    NaN
 324      Maine           234.0            174.0                    NaN
 325      Maine             NaN              NaN                    NaN
 326      Maine          4264.0           1397.0                  630.0
 327      Maine          4536.0           1080.0                  640.0
 328      Maine          3909.0           1323.0                  620.0
 329      Maine             NaN              NaN                    NaN
 330      Maine             NaN              NaN                    NaN
 331      Maine             NaN              NaN                    NaN
 332      Maine          1743.0           1200.0                  470.0
 333      Maine           549.0            532.0                    NaN
 334      Maine           521.0            423.0                    NaN
 335      Maine          4783.0           3890.0                  480.0
 336      Maine             NaN              NaN                    NaN
 337      Maine           486.0            380.0                    NaN
 338      Maine           300.0            270.0                    NaN
 339      Maine            47.0             44.0                    NaN
 340      Maine          1444.0           1283.0                  470.0
 341      Maine           320.0            283.0                  455.0
 342      Maine             NaN              NaN                    NaN
 343      Maine          2926.0           2410.0                  450.0
 344      Maine           515.0            492.0                  420.0
 345      Maine           470.0            426.0                    NaN
 346      Maine             NaN              NaN                    NaN
 347      Maine             NaN              NaN                    NaN

      sat_crit_read_75_pctl  sat_math_25_pctl  sat_math_75_pctl  \
 0                      NaN               NaN               NaN
 1                      NaN               NaN               NaN
 2                      NaN               NaN               NaN
 3                    725.0             640.0             745.0
 4                      NaN               NaN               NaN
 5                      NaN               NaN               NaN
 6                    510.0             400.0             475.0
 7                      NaN               NaN               NaN
 8                    590.0             480.0             600.0
 9                      NaN               NaN               NaN
 10                   560.0             480.0             580.0
 11                     NaN               NaN               NaN
 12                   570.0             470.0             580.0
 13                     NaN               NaN               NaN
 14                   520.0             390.0             500.0
 15                   550.0             430.0             540.0
 16                     NaN               NaN               NaN
 17                     NaN               NaN               NaN
 18                     NaN               NaN               NaN
 19                   530.0             430.0             540.0
 20                     NaN               NaN               NaN
 21                     NaN               NaN               NaN
 22                     NaN               NaN               NaN
 23                   720.0             640.0             740.0
 24                     NaN               NaN               NaN
 25                     NaN               NaN               NaN
 26                     NaN               NaN               NaN
 27                   480.0             400.0             500.0
 28                     NaN               NaN               NaN
 29                   600.0             480.0             610.0
 ..                     ...               ...               ...
 318                  540.0             430.0             560.0
 319                  550.0             450.0             540.0
 320                  500.0             410.0             510.0
 321                    NaN               NaN               NaN
 322                    NaN               NaN               NaN
 323                    NaN               NaN               NaN
 324                    NaN               NaN               NaN
 325                    NaN               NaN               NaN
 326                  700.0             640.0             700.0
 327                  730.0             640.0             710.0
 328                  700.0             630.0             710.0
 329                    NaN               NaN               NaN
 330                    NaN               NaN               NaN
 331                    NaN               NaN               NaN
 332                  580.0             460.0             570.0
 333                    NaN               NaN               NaN
 334                    NaN               NaN               NaN
 335                  590.0             490.0             600.0
 336                    NaN               NaN               NaN
 337                    NaN               NaN               NaN
 338                    NaN               NaN               NaN
 339                    NaN               NaN               NaN
 340                  580.0             480.0             580.0
 341                  585.0             415.0             530.0
 342                    NaN               NaN               NaN
 343                  560.0             440.0             550.0
 344                  510.0             400.0             530.0
 345                    NaN               NaN               NaN
 346                    NaN               NaN               NaN
 347                    NaN               NaN               NaN

      act_composite_25_pctl  act_composite_75_pctl  act_english_25_pctl  \
 0                      NaN                    NaN                  NaN
 1                      NaN                    NaN                  NaN
 2                      NaN                    NaN                  NaN
 3                     30.0                   33.0                 30.0
 4                      NaN                    NaN                  NaN
 5                      NaN                    NaN                  NaN
 6                     16.0                   22.0                 12.0
 7                      NaN                    NaN                  NaN
 8                     21.0                   26.0                 20.0
 9                      NaN                    NaN                  NaN
 10                    21.0                   25.0                 19.0
 11                     NaN                    NaN                  NaN
 12                    21.0                   26.0                 20.0
 13                     NaN                    NaN                  NaN
 14                    20.0                   23.0                 19.0
 15                    19.0                   25.0                 17.0
 16                     NaN                    NaN                  NaN
 17                     NaN                    NaN                  NaN
 18                     NaN                    NaN                  NaN
 19                    17.0                   23.0                 16.0
 20                     NaN                    NaN                  NaN
 21                     NaN                    NaN                  NaN
 22                     NaN                    NaN                  NaN
 23                    29.0                   32.0                 29.0
 24                     NaN                    NaN                  NaN
 25                     NaN                    NaN                  NaN
 26                     NaN                    NaN                  NaN
 27                    15.0                   19.0                 13.0
 28                     NaN                    NaN                  NaN
 29                    21.0                   28.0                  NaN
 ..                     ...                    ...                  ...
 318                    NaN                    NaN                  NaN
 319                    NaN                    NaN                  NaN
 320                    NaN                    NaN                  NaN
 321                    NaN                    NaN                  NaN
 322                    NaN                    NaN                  NaN
 323                    NaN                    NaN                  NaN
 324                    NaN                    NaN                  NaN
 325                    NaN                    NaN                  NaN
 326                    NaN                    NaN                  NaN
 327                    NaN                    NaN                  NaN
 328                   26.0                   30.0                 26.0
 329                    NaN                    NaN                  NaN
 330                    NaN                    NaN                  NaN

In [9]:
check(education[0])

variable        object
label           object
description     object
source          object
source2        float64
dtype: object

In [10]:
check(education[1])

year                       int64
unitid                     int64
inst_name                 object
state_name                object
number_applied           float64
number_admitted          float64
sat_crit_read_25_pctl    float64
sat_crit_read_75_pctl    float64
sat_math_25_pctl         float64
sat_math_75_pctl         float64
act_composite_25_pctl    float64
act_composite_75_pctl    float64
act_english_25_pctl      float64
act_english_75_pctl      float64
act_math_25_pctl         float64
act_math_75_pctl         float64
inst_control              object
institution_level         object
dtype: object

In [11]:
check(education[2])

year                int64
unitid              int64
inst_name          object
state_name         object
level_of_study     object
enrollment_fall     int64
dtype: object

In [12]:
check(education[3])

year                    int64
unitid                  int64
inst_name              object
state_name             object
state_of_residence     object
type_of_freshman       object
enrollment_fall       float64
dtype: object

In [13]:
#Separate data frames
admit=education[1]
level=education[2]
freshman=education[3]

In [53]:
admit['acceptance_rate']=admit['number_admitted']/admit['number_applied']
admit

,year,unitid,inst_name,state_name,number_applied,number_admitted,sat_crit_read_25_pctl,sat_crit_read_75_pctl,sat_math_25_pctl,sat_math_75_pctl,act_composite_25_pctl,act_composite_75_pctl,act_english_25_pctl,act_english_75_pctl,act_math_25_pctl,act_math_75_pctl,inst_control,institution_level,acceptance_rate
0,2016,160959,College of the Atlantic,Maine,485.0,314.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,0.647423
1,2016,160977,Bates College,Maine,5356.0,1213.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,0.226475
2,2016,161004,Bowdoin College,Maine,6799.0,1009.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,0.148404
3,2016,161086,Colby College,Maine,9833.0,1840.0,630.0,725.0,640.0,745.0,30.0,33.0,30.0,34.0,27.0,32.0,Private not-for-profit,Four or more years,0.187125
4,2016,161217,University of Maine at Augusta,Maine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Public,Four or more years,NaN
5,2016,161226,University of Maine at Farmington,Maine,1880.0,1512.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Public,Four or more years,0.804255
6,2016,161235,University of Maine at Fort Kent,Maine,481.0,392.0,390.0,510.0,400.0,475.0,16.0,22.0,12.0,22.0,16.0,20.0,Public,Four or more years,0.814969
7,2016,161244,University of Maine at Machias,Maine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Public,Four or more years,NaN
8,2016,161253,University of Maine,Maine,12952.0,11625.0,470.0,590.0,480.0,600.0,21.0,26.0,20.0,25.0,20.0,26.0,Public,Four or more years,0.897545
9,2016,161280,University of Maine-System Central Office,Maine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Public,Four or more years,NaN
10,2016,161299,Maine Maritime Academy,Maine,882.0,666.0,450.0,560.0,480.0,580.0,21.0,25.0,19.0,24.0,21.0,27.0,Public,Four or more years,0.755102
11,2016,161341,University of Maine at Presque Isle,Maine,1491.0,1293.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Public,Four or more years,0.867203
12,2016,161457,University of New England,Maine,4883.0,4056.0,470.0,570.0,470.0,580.0,21.0,26.0,20.0,25.0,20.0,26.0,Private not-for-profit,Four or more years,0.830637
13,2016,161509,Maine College of Art,Maine,529.0,457.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,0.863894
14,2016,161518,Saint Joseph's College of Maine,Maine,1323.0,1033.0,420.0,520.0,390.0,500.0,20.0,23.0,19.0,24.0,17.0,25.0,Private not-for-profit,Four or more years,0.780801
15,2016,161554,University of Southern Maine,Maine,4111.0,3299.0,440.0,550.0,430.0,540.0,19.0,25.0,17.0,24.0,18.0,25.0,Public,Four or more years,0.802481
16,2016,161563,Thomas College,Maine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,NaN
17,2016,161572,Unity College,Maine,991.0,920.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,0.928355
18,2016,462044,Institute for Doctoral Studies in the Visual Arts,Maine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,NaN
19,2016,487524,Husson University,Maine,2460.0,1974.0,430.0,530.0,430.0,540.0,17.0,23.0,16.0,23.0,17.0,24.0,Private not-for-profit,Four or more years,0.802439
20,2015,160959,College of the Atlantic,Maine,400.0,302.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,0.755000
21,2015,160977,Bates College,Maine,5651.0,1231.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,0.217838
22,2015,161004,Bowdoin College,Maine,6790.0,1010.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,0.148748
23,2015,161086,Colby College,Maine,7593.0,1710.0,630.0,720.0,640.0,740.0,29.0,32.0,29.0,34.0,27.0,33.0,Private not-for-profit,Four or more years,0.225207
24,2015,161165,Husson University,Maine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,NaN
25,2015,161217,University of Maine at Augusta,Maine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Public,Four or more years,NaN
26,2015,161226,University of Maine at Farmington,Maine,1614.0,1346.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Public,Four or more years,0.833953
27,2015,161235,University of Maine at Fort Kent,Maine,215.0,192.0,400.0,480.0,400.0,500.0,15.0,19.0,13.0,18.0,17.0,22.0,Public,Four or more years,0.893023
28,2015,161244,University of Maine at Machias,Maine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Public,Four or more years,NaN
29,2015,161253,University of Maine,Maine,11044.0,10073.0,480.0,600.0,480.0,610.0,21.0,28.0,NaN,NaN,NaN,NaN,Public,Four or more years,0.912079
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318,2002,161518,SAINT JOSEPHS COLLEGE,Maine,1129.0,925.0,420.0,540.0,430.0,560.0,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,0.819309
319,2002,161554,UNIVERSITY OF SOUTHERN MAINE,Maine,3664.0,2741.0,450.0,550.0,450.0,540.0,NaN,NaN,NaN,NaN,NaN,NaN,Public,Four or more years,0.748090
320,2002,161563,THOMAS COLLEGE,Maine,487.0,393.0,400.0,500.0,410.0,510.0,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,0.806982
321,2002,161572,UNITY COLLEGE,Maine,625.0,502.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,0.803200
322,2002,373827,NEW ENGLAND SCHOOL OF COMMUNICATIONS,Maine,240.0,159.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,0.662500
323,2002,407230,BANGOR THEOLOGICAL SEMINARY,Maine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,NaN
324,2001,160959,COLLEGE OF THE ATLANTIC,Maine,234.0,174.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,0.743590
325,2001,160968,BANGOR THEOLOGICAL SEMINARY,Maine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,NaN
326,2001,160977,BATES COLLEGE,Maine,4264.0,1397.0,630.0,700.0,640.0,700.0,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,0.327627
327,2001,161004,BOWDOIN COLLEGE,Maine,4536.0,1080.0,640.0,730.0,640.0,710.0,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,0.238095
328,2001,161086,COLBY COLLEGE,Maine,3909.0,1323.0,620.0,700.0,630.0,710.0,26.0,30.0,26.0,30.0,26.0,31.0,Private not-for-profit,Four or more years,0.338450
329,2001,161147,FAITH SCHOOL OF THEOLOGY,Maine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,NaN
330,2001,161165,HUSSON COLLEGE,Maine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,NaN
331,2001,161217,UNIVERSITY OF MAINE AT AUGUSTA,Maine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Public,Four or more years,NaN
332,2001,161226,UNIVERSITY OF MAINE AT FARMINGTON,Maine,1743.0,1200.0,470.0,580.0,460.0,570.0,NaN,NaN,NaN,NaN,NaN,NaN,Public,Four or more years,0.688468
333,2001,161235,UNIVERSITY OF MAINE AT FORT KENT,Maine,549.0,532.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Public,Four or more years,0.969035
334,2001,161244,UNIVERSITY OF MAINE AT MACHIAS,Maine,521.0,423.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Public,Four or more years,0.811900
335,2001,161253,UNIVERSITY OF MAINE,Maine,4783.0,3890.0,480.0,590.0,490.0,600.0,NaN,NaN,NaN,NaN,NaN,NaN,Public,Four or more years,0.813297
336,2001,161280,UNIVERSITY OF MAINE SYSTEM CENTRAL OFFICE,Maine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Public,Four or more years,NaN
337,2001,161299,MAINE MARITIME ACADEMY,Maine,486.0,380.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Public,Four or more years,0.781893
338,2001,161341,UNIVERSITY OF MAINE AT PRESQUE ISLE,Maine,300.0,270.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Public,Four or more years,0.900000
339,2001,161448,NEW ENGLAND BAPTIST BIBLE COLLEGE,Maine,47.0,44.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,0.936170
340,2001,161457,UNIVERSITY OF NEW ENGLAND-UNIVERSITY CAMPUS,Maine,1444.0,1283.0,470.0,580.0,480.0,580.0,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,0.888504
341,2001,161509,MAINE COLLEGE OF ART,Maine,320.0,283.0,455.0,585.0,415.0,530.0,18.0,24.0,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,0.884375
342,2001,161518,SAINT JOSEPHS COLLEGE,Maine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,NaN
343,2001,161554,UNIVERSITY OF SOUTHERN MAINE,Maine,2926.0,2410.0,450.0,560.0,440.0,550.0,NaN,NaN,NaN,NaN,NaN,NaN,Public,Four or more years,0.823650
344,2001,161563,THOMAS COLLEGE,Maine,515.0,492.0,420.0,510.0,400.0,530.0,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,0.955340
345,2001,161572,UNITY COLLEGE,Maine,470.0,426.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,0.906383
346,2001,373827,NEW ENGLAND SCHOOL OF COMMUNICATIONS,Maine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,NaN
347,2001,407230,BANGOR THEOLOGICAL SEMINARY,Maine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,NaN

In [87]:
#Summary stats
print(np.mean(admit['acceptance_rate']))
print(np.std(admit['acceptance_rate']))
print(np.min(admit[admit['acceptance_rate']>0]['acceptance_rate']))
print(np.max(admit['acceptance_rate']))
admit.describe()

0.6787589313918648
0.22986986106376603
0.14840417708486542
0.9805352798053528

,year,unitid,number_applied,number_admitted,sat_crit_read_25_pctl,sat_crit_read_75_pctl,sat_math_25_pctl,sat_math_75_pctl,act_composite_25_pctl,act_composite_75_pctl,act_english_25_pctl,act_english_75_pctl,act_math_25_pctl,act_math_75_pctl,acceptance_rate
count,348.000000,348.000000,262.000000,262.000000,163.000000,163.000000,163.000000,163.000000,116.000000,116.000000,91.000000,91.000000,91.000000,91.000000,257.000000
mean,2008.379310,178913.146552,2291.335878,1309.492366,480.398773,583.558282,482.607362,585.276074,20.181034,25.362069,19.747253,25.758242,19.923077,25.989011,0.678759
std,4.643464,64554.791849,2394.662123,1579.722898,81.236550,75.108407,83.836145,74.150022,4.390898,3.786467,5.338734,4.648394,4.351834,3.920018,0.230318
min,2001.000000,160959.000000,0.000000,0.000000,370.000000,480.000000,350.000000,470.000000,15.000000,19.000000,12.000000,18.000000,15.000000,19.000000,0.000000
25%,2004.000000,161165.000000,472.000000,364.250000,430.000000,530.000000,430.000000,535.000000,17.000000,23.000000,16.000000,22.500000,17.000000,23.000000,0.640327
50%,2008.000000,161280.000000,1259.500000,1006.500000,450.000000,560.000000,460.000000,570.000000,19.000000,25.000000,18.000000,24.000000,18.000000,25.000000,0.771151
75%,2012.000000,161518.000000,4110.500000,1397.000000,480.000000,590.000000,490.000000,600.000000,21.000000,27.000000,20.500000,28.500000,21.000000,27.000000,0.826360
max,2016.000000,487524.000000,12952.000000,11625.000000,680.000000,760.000000,680.000000,760.000000,31.000000,33.000000,31.000000,35.000000,29.000000,34.000000,0.980535

In [18]:
colleges=admit.reset_index()['inst_name'].unique()
for college in colleges:
    college=college.lower()
    
colleges

array(['College of the Atlantic', 'Bates College', 'Bowdoin College',
       'Colby College', 'University of Maine at Augusta',
       'University of Maine at Farmington',
       'University of Maine at Fort Kent',
       'University of Maine at Machias', 'University of Maine',
       'University of Maine-System Central Office',
       'Maine Maritime Academy', 'University of Maine at Presque Isle',
       'University of New England', 'Maine College of Art',
       "Saint Joseph's College of Maine", 'University of Southern Maine',
       'Thomas College', 'Unity College',
       'Institute for Doctoral Studies in the Visual Arts',
       'Husson University', 'New England School of Communications',
       'Bangor Theological Seminary',
       'University of Maine System Central Office', 'Husson College',
       'New England Baptist Bible College', 'Saint Josephs College',
       'COLLEGE OF THE ATLANTIC', 'BANGOR THEOLOGICAL SEMINARY',
       'BATES COLLEGE', 'BOWDOIN COLLEGE', 'COLBY COLLEGE',
       'HUSSON COLLEGE', 'UNIVERSITY OF MAINE AT AUGUSTA',
       'UNIVERSITY OF MAINE AT FARMINGTON',
       'UNIVERSITY OF MAINE AT FORT KENT',
       'UNIVERSITY OF MAINE AT MACHIAS', 'UNIVERSITY OF MAINE',
       'UNIVERSITY OF MAINE SYSTEM CENTRAL OFFICE',
       'MAINE MARITIME ACADEMY', 'UNIVERSITY OF MAINE AT PRESQUE ISLE',
       'NEW ENGLAND BAPTIST BIBLE COLLEGE', 'UNIVERSITY OF NEW ENGLAND',
       'MAINE COLLEGE OF ART', 'SAINT JOSEPHS COLLEGE',
       'UNIVERSITY OF SOUTHERN MAINE', 'THOMAS COLLEGE', 'UNITY COLLEGE',
       'NEW ENGLAND SCHOOL OF COMMUNICATIONS', 'FAITH SCHOOL OF THEOLOGY',
       'UNIVERSITY OF NEW ENGLAND-UNIVERSITY CAMPUS'], dtype=object)

In [17]:
def plot_one_rate(college, color='red', size=8):
    plot = figure(title='Acceptance Rates Over Time For '+college, x_axis_label='Year', 
              y_axis_label='Rate')
    plot.circle(admit[admit['inst_name']==college]['year'], 
                 admit[admit['inst_name']==college]['acceptance_rate'],
              legend=college, fill_color=color, size=size)
    #plot2 = figure(title='Acceptance Rates Over Time For '+college2, x_axis_label='Year', 
     #         y_axis_label='Rate', x
        
    #show(plot)
    return(plot)

In [18]:
@interact(college=colleges)
def make_one_plot(college=colleges[2]):
    plot=plot_one_rate(college)
    show(plot)

interactive(children=(Dropdown(description='college', index=2, options=('College of the Atlantic', 'Bates Coll…

In [19]:
#Compare rates for two colleges.
def plot_rate(college1, college2, color='red', size=8):
    plot1 = figure(title='Acceptance Rates Over Time For '+college1, x_axis_label='Year', 
              y_axis_label='Rate')
    plot1.circle(admit[admit['inst_name']==college1]['year'], 
                 admit[admit['inst_name']==college1]['acceptance_rate'],
              legend=college1, fill_color=color, size=size)
    plot2 = figure(title='Acceptance Rates Over Time For '+college2, x_axis_label='Year', 
              y_axis_label='Rate', x_range=plot1.x_range, y_range=plot1.y_range)
    plot2.circle(admit[admit['inst_name']==college2]['year'], 
                 admit[admit['inst_name']==college2]['acceptance_rate'],
              legend=college2, fill_color=color, size=size)
    plot=gridplot([[plot1],[plot2]])
    #show(plot)
    return(plot)

In [20]:
@interact(college1=colleges, college2=colleges)#colleges=admit['inst_name'])
def make_rate_plot(college1=colleges[2],college2=colleges[3]):
    plot=plot_rate(college1, college2)
    show(plot)

interactive(children=(Dropdown(description='college1', index=2, options=('College of the Atlantic', 'Bates Col…

In [22]:
#Plot by residence 
def plot_residence(college,df):
    counts=df[df['inst_name']==college]['state_of_residence'].value_counts()
    plot=figure(title='Residents by State For '+college, x_axis_label='State', 
              y_axis_label='Number', 
                x_range=df.reset_index()['state_of_residence'].unique())
    plot.vbar(x=df['state_of_residence'], top=counts, width=0.4)
    #show(plot)
    return plot

In [27]:
@interact(college=colleges)
def make_res_plot(college=colleges[2]):
    plot=plot_residence(college,freshman)
    show(plot)

interactive(children=(Dropdown(description='college', index=2, options=('College of the Atlantic', 'Bates Coll…

In [28]:
from sklearn.linear_model import LinearRegression
model = LinearRegression(fit_intercept=False)

In [69]:
#Make a categorical variable based on acceptance rate.  
admit["Selectivity"]=pd.cut(admit['acceptance_rate'], bins=[0,.20,.40,.60,1.0],
                           include_lowest=True,
                           labels=['Highly Selective', 'Selective',
                                  'Somewhat Selective', 'Not Selective'])

In [70]:
admit

,year,unitid,inst_name,state_name,number_applied,number_admitted,sat_crit_read_25_pctl,sat_crit_read_75_pctl,sat_math_25_pctl,sat_math_75_pctl,act_composite_25_pctl,act_composite_75_pctl,act_english_25_pctl,act_english_75_pctl,act_math_25_pctl,act_math_75_pctl,inst_control,institution_level,acceptance_rate,Selectivity
0,2016,160959,College of the Atlantic,Maine,485.0,314.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,0.647423,Not Selective
1,2016,160977,Bates College,Maine,5356.0,1213.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,0.226475,Selective
2,2016,161004,Bowdoin College,Maine,6799.0,1009.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,0.148404,Highly Selective
3,2016,161086,Colby College,Maine,9833.0,1840.0,630.0,725.0,640.0,745.0,30.0,33.0,30.0,34.0,27.0,32.0,Private not-for-profit,Four or more years,0.187125,Highly Selective
4,2016,161217,University of Maine at Augusta,Maine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Public,Four or more years,NaN,NaN
5,2016,161226,University of Maine at Farmington,Maine,1880.0,1512.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Public,Four or more years,0.804255,Not Selective
6,2016,161235,University of Maine at Fort Kent,Maine,481.0,392.0,390.0,510.0,400.0,475.0,16.0,22.0,12.0,22.0,16.0,20.0,Public,Four or more years,0.814969,Not Selective
7,2016,161244,University of Maine at Machias,Maine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Public,Four or more years,NaN,NaN
8,2016,161253,University of Maine,Maine,12952.0,11625.0,470.0,590.0,480.0,600.0,21.0,26.0,20.0,25.0,20.0,26.0,Public,Four or more years,0.897545,Not Selective
9,2016,161280,University of Maine-System Central Office,Maine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Public,Four or more years,NaN,NaN
10,2016,161299,Maine Maritime Academy,Maine,882.0,666.0,450.0,560.0,480.0,580.0,21.0,25.0,19.0,24.0,21.0,27.0,Public,Four or more years,0.755102,Not Selective
11,2016,161341,University of Maine at Presque Isle,Maine,1491.0,1293.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Public,Four or more years,0.867203,Not Selective
12,2016,161457,University of New England,Maine,4883.0,4056.0,470.0,570.0,470.0,580.0,21.0,26.0,20.0,25.0,20.0,26.0,Private not-for-profit,Four or more years,0.830637,Not Selective
13,2016,161509,Maine College of Art,Maine,529.0,457.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,0.863894,Not Selective
14,2016,161518,Saint Joseph's College of Maine,Maine,1323.0,1033.0,420.0,520.0,390.0,500.0,20.0,23.0,19.0,24.0,17.0,25.0,Private not-for-profit,Four or more years,0.780801,Not Selective
15,2016,161554,University of Southern Maine,Maine,4111.0,3299.0,440.0,550.0,430.0,540.0,19.0,25.0,17.0,24.0,18.0,25.0,Public,Four or more years,0.802481,Not Selective
16,2016,161563,Thomas College,Maine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,NaN,NaN
17,2016,161572,Unity College,Maine,991.0,920.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,0.928355,Not Selective
18,2016,462044,Institute for Doctoral Studies in the Visual Arts,Maine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,NaN,NaN
19,2016,487524,Husson University,Maine,2460.0,1974.0,430.0,530.0,430.0,540.0,17.0,23.0,16.0,23.0,17.0,24.0,Private not-for-profit,Four or more years,0.802439,Not Selective
20,2015,160959,College of the Atlantic,Maine,400.0,302.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,0.755000,Not Selective
21,2015,160977,Bates College,Maine,5651.0,1231.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,0.217838,Selective
22,2015,161004,Bowdoin College,Maine,6790.0,1010.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,0.148748,Highly Selective
23,2015,161086,Colby College,Maine,7593.0,1710.0,630.0,720.0,640.0,740.0,29.0,32.0,29.0,34.0,27.0,33.0,Private not-for-profit,Four or more years,0.225207,Selective
24,2015,161165,Husson University,Maine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,NaN,NaN
25,2015,161217,University of Maine at Augusta,Maine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Public,Four or more years,NaN,NaN
26,2015,161226,University of Maine at Farmington,Maine,1614.0,1346.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Public,Four or more years,0.833953,Not Selective
27,2015,161235,University of Maine at Fort Kent,Maine,215.0,192.0,400.0,480.0,400.0,500.0,15.0,19.0,13.0,18.0,17.0,22.0,Public,Four or more years,0.893023,Not Selective
28,2015,161244,University of Maine at Machias,Maine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Public,Four or more years,NaN,NaN
29,2015,161253,University of Maine,Maine,11044.0,10073.0,480.0,600.0,480.0,610.0,21.0,28.0,NaN,NaN,NaN,NaN,Public,Four or more years,0.912079,Not Selective
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318,2002,161518,SAINT JOSEPHS COLLEGE,Maine,1129.0,925.0,420.0,540.0,430.0,560.0,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,0.819309,Not Selective
319,2002,161554,UNIVERSITY OF SOUTHERN MAINE,Maine,3664.0,2741.0,450.0,550.0,450.0,540.0,NaN,NaN,NaN,NaN,NaN,NaN,Public,Four or more years,0.748090,Not Selective
320,2002,161563,THOMAS COLLEGE,Maine,487.0,393.0,400.0,500.0,410.0,510.0,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,0.806982,Not Selective
321,2002,161572,UNITY COLLEGE,Maine,625.0,502.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,0.803200,Not Selective
322,2002,373827,NEW ENGLAND SCHOOL OF COMMUNICATIONS,Maine,240.0,159.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,0.662500,Not Selective
323,2002,407230,BANGOR THEOLOGICAL SEMINARY,Maine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,NaN,NaN
324,2001,160959,COLLEGE OF THE ATLANTIC,Maine,234.0,174.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,0.743590,Not Selective
325,2001,160968,BANGOR THEOLOGICAL SEMINARY,Maine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,NaN,NaN
326,2001,160977,BATES COLLEGE,Maine,4264.0,1397.0,630.0,700.0,640.0,700.0,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,0.327627,Selective
327,2001,161004,BOWDOIN COLLEGE,Maine,4536.0,1080.0,640.0,730.0,640.0,710.0,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,0.238095,Selective
328,2001,161086,COLBY COLLEGE,Maine,3909.0,1323.0,620.0,700.0,630.0,710.0,26.0,30.0,26.0,30.0,26.0,31.0,Private not-for-profit,Four or more years,0.338450,Selective
329,2001,161147,FAITH SCHOOL OF THEOLOGY,Maine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,NaN,NaN
330,2001,161165,HUSSON COLLEGE,Maine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,NaN,NaN
331,2001,161217,UNIVERSITY OF MAINE AT AUGUSTA,Maine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Public,Four or more years,NaN,NaN
332,2001,161226,UNIVERSITY OF MAINE AT FARMINGTON,Maine,1743.0,1200.0,470.0,580.0,460.0,570.0,NaN,NaN,NaN,NaN,NaN,NaN,Public,Four or more years,0.688468,Not Selective
333,2001,161235,UNIVERSITY OF MAINE AT FORT KENT,Maine,549.0,532.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Public,Four or more years,0.969035,Not Selective
334,2001,161244,UNIVERSITY OF MAINE AT MACHIAS,Maine,521.0,423.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Public,Four or more years,0.811900,Not Selective
335,2001,161253,UNIVERSITY OF MAINE,Maine,4783.0,3890.0,480.0,590.0,490.0,600.0,NaN,NaN,NaN,NaN,NaN,NaN,Public,Four or more years,0.813297,Not Selective
336,2001,161280,UNIVERSITY OF MAINE SYSTEM CENTRAL OFFICE,Maine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Public,Four or more years,NaN,NaN
337,2001,161299,MAINE MARITIME ACADEMY,Maine,486.0,380.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Public,Four or more years,0.781893,Not Selective
338,2001,161341,UNIVERSITY OF MAINE AT PRESQUE ISLE,Maine,300.0,270.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Public,Four or more years,0.900000,Not Selective
339,2001,161448,NEW ENGLAND BAPTIST BIBLE COLLEGE,Maine,47.0,44.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,0.936170,Not Selective
340,2001,161457,UNIVERSITY OF NEW ENGLAND-UNIVERSITY CAMPUS,Maine,1444.0,1283.0,470.0,580.0,480.0,580.0,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,0.888504,Not Selective
341,2001,161509,MAINE COLLEGE OF ART,Maine,320.0,283.0,455.0,585.0,415.0,530.0,18.0,24.0,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,0.884375,Not Selective
342,2001,161518,SAINT JOSEPHS COLLEGE,Maine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,NaN,NaN
343,2001,161554,UNIVERSITY OF SOUTHERN MAINE,Maine,2926.0,2410.0,450.0,560.0,440.0,550.0,NaN,NaN,NaN,NaN,NaN,NaN,Public,Four or more years,0.823650,Not Selective
344,2001,161563,THOMAS COLLEGE,Maine,515.0,492.0,420.0,510.0,400.0,530.0,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,0.955340,Not Selective
345,2001,161572,UNITY COLLEGE,Maine,470.0,426.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,0.906383,Not Selective
346,2001,373827,NEW ENGLAND SCHOOL OF COMMUNICATIONS,Maine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,NaN,NaN
347,2001,407230,BANGOR THEOLOGICAL SEMINARY,Maine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Private not-for-profit,Four or more years,NaN,NaN

# Now, the models

In [71]:
Z=admit[['sat_math_75_pctl','act_composite_75_pctl', 'Selectivity']].dropna()
X=Z[['sat_math_75_pctl','act_composite_75_pctl']]
Y=Z['Selectivity']
X

     sat_math_75_pctl  act_composite_75_pctl
3               745.0                   33.0
6               475.0                   22.0
8               600.0                   26.0
10              580.0                   25.0
12              580.0                   26.0
14              500.0                   23.0
15              540.0                   25.0
19              540.0                   23.0
23              740.0                   32.0
27              500.0                   19.0
29              610.0                   28.0
31              590.0                   26.0
33              590.0                   29.0
35              540.0                   26.0
36              550.0                   25.0
41              540.0                   23.0
45              720.0                   32.0
46              530.0                   21.0
49              500.0                   19.0
51              600.0                   27.0
53              580.0                   24.0
55              580.0                   26.0
58              550.0                   24.0
66              750.0                   33.0
67              720.0                   32.0
68              550.0                   21.0
71              500.0                   27.0
72              520.0                   25.0
73              610.0                   26.0
75              580.0                   24.0
..                ...                    ...
209             540.0                   23.0
210             510.0                   22.0
217             720.0                   31.0
222             520.0                   25.0
223             600.0                   25.0
225             580.0                   23.0
229             580.0                   20.0
231             540.0                   23.0
232             530.0                   25.0
239             710.0                   31.0
244             540.0                   25.0
245             600.0                   26.0
247             580.0                   22.0
251             570.0                   20.0
253             550.0                   23.0
254             520.0                   24.0
261             710.0                   31.0
266             540.0                   21.0
267             600.0                   27.0
269             590.0                   26.0
273             560.0                   20.0
274             550.0                   20.0
275             550.0                   24.0
288             520.0                   23.0
295             560.0                   20.0
310             520.0                   26.0
313             610.0                   24.0
317             540.0                   26.0
328             710.0                   30.0
341             530.0                   24.0

[116 rows x 2 columns]

In [72]:
Y

3      Highly Selective
6         Not Selective
8         Not Selective
10        Not Selective
12        Not Selective
14        Not Selective
15        Not Selective
19        Not Selective
23            Selective
27        Not Selective
29        Not Selective
31        Not Selective
33        Not Selective
35        Not Selective
36        Not Selective
41        Not Selective
45            Selective
46        Not Selective
49        Not Selective
51        Not Selective
53        Not Selective
55        Not Selective
58        Not Selective
66     Highly Selective
67            Selective
68        Not Selective
71        Not Selective
72        Not Selective
73        Not Selective
75        Not Selective
             ...
209       Not Selective
210       Not Selective
217           Selective
222       Not Selective
223       Not Selective
225       Not Selective
229       Not Selective
231       Not Selective
232       Not Selective
239           Selective
244       Not Selective
245       Not Selective
247       Not Selective
251       Not Selective
253       Not Selective
254       Not Selective
261           Selective
266       Not Selective
267       Not Selective
269       Not Selective
273       Not Selective
274       Not Selective
275       Not Selective
288       Not Selective
295       Not Selective
310       Not Selective
313           Selective
317       Not Selective
328           Selective
341       Not Selective
Name: Selectivity, Length: 116, dtype: category
Categories (4, object): [Highly Selective < Selective < Somewhat Selective < Not Selective]

In [73]:
X.shape

(116, 2)

In [74]:
Y.shape

(116,)

# Try the SVC model, as in class.

In [99]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.20, random_state=123)

In [89]:
print(X_train.shape)
print(Y_train.shape)

print(X_test.shape)
print(Y_test.shape)

(81, 2)
(81,)
(35, 2)
(35,)

In [100]:
from sklearn.svm import SVC
model = SVC(gamma='auto')
model.fit(X_train, Y_train)
predict = model.predict(X_test)

In [91]:
predict

array(['Not Selective', 'Not Selective', 'Highly Selective',
       'Not Selective', 'Not Selective', 'Not Selective', 'Not Selective',
       'Not Selective', 'Not Selective', 'Not Selective', 'Not Selective',
       'Not Selective', 'Not Selective', 'Not Selective', 'Not Selective',
       'Selective', 'Not Selective', 'Not Selective', 'Selective',
       'Not Selective', 'Selective', 'Not Selective', 'Not Selective',
       'Selective', 'Not Selective', 'Not Selective', 'Not Selective',
       'Highly Selective', 'Not Selective', 'Not Selective', 'Selective',
       'Not Selective', 'Not Selective', 'Not Selective', 'Not Selective'],
      dtype=object)

In [60]:
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

In [61]:
r2_score(Y_test, predict)
mean_squared_error(Y_test, predict)

0.0324088046360858

In [92]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [101]:
accuracy_score(Y_test, predict)

0.875

In [94]:
confusion_matrix(Y_test, predict)

array([[ 2,  2,  0],
       [ 0, 25,  0],
       [ 0,  1,  5]])

In [95]:
print(classification_report(Y_test, predict))

                  precision    recall  f1-score   support

Highly Selective       1.00      0.50      0.67         4
   Not Selective       0.89      1.00      0.94        25
       Selective       1.00      0.83      0.91         6

        accuracy                           0.91        35
       macro avg       0.96      0.78      0.84        35
    weighted avg       0.92      0.91      0.91        35

# Test Harness--Model Selection

In [96]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold

In [97]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB

models = [('Dec Tree', DecisionTreeClassifier()), 
          ('Lin Disc', LinearDiscriminantAnalysis()), ('Gauss', GaussianNB()), 
          ('SVC', SVC(gamma='auto'))]

In [102]:
results = []

for name, model in models:
    kf = StratifiedKFold(n_splits=10, random_state=123)
    res = cross_val_score(model, X_train, Y_train, cv=kf, scoring='accuracy') #Not kfold
    res_mean = round(res.mean(), 4) #Constraints, tougher with bigger data. 
    res_std  = round(res.std(), 4)
    results.append((name, res_mean, res_std))
    
results

//anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:657: Warning: The least populated class in y has only 5 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)
//anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:657: Warning: The least populated class in y has only 5 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)
//anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:657: Warning: The least populated class in y has only 5 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)
//anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:657: Warning: The least populated class in y has only 5 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)

[('Dec Tree', 0.97, 0.064),
 ('Lin Disc', 0.97, 0.064),
 ('Gauss', 0.99, 0.03),
 ('SVC', 0.97, 0.064)]

# Try the Gaussian model, see if it predicts better than SVC.

In [103]:
Gaussmodel=GaussianNB()
Gaussmodel.fit(X_train,Y_train)
Gausspredict=Gaussmodel.predict(X_test)

In [104]:
Gausspredict

array(['Not Selective', 'Not Selective', 'Highly Selective',
       'Not Selective', 'Not Selective', 'Not Selective', 'Not Selective',
       'Not Selective', 'Not Selective', 'Highly Selective',
       'Not Selective', 'Selective', 'Not Selective', 'Highly Selective',
       'Not Selective', 'Selective', 'Not Selective', 'Not Selective',
       'Selective', 'Not Selective', 'Selective', 'Not Selective',
       'Not Selective', 'Selective'], dtype='<U16')

In [105]:
accuracy_score(Y_test, Gausspredict)

1.0

In [106]:
confusion_matrix(Y_test, Gausspredict)

array([[ 3,  0,  0],
       [ 0, 16,  0],
       [ 0,  0,  5]])

In [107]:
print(classification_report(Y_test, Gausspredict))

                  precision    recall  f1-score   support

Highly Selective       1.00      1.00      1.00         3
   Not Selective       1.00      1.00      1.00        16
       Selective       1.00      1.00      1.00         5

        accuracy                           1.00        24
       macro avg       1.00      1.00      1.00        24
    weighted avg       1.00      1.00      1.00        24

# Final Thoughts

I used the education data from assignment 6; most of the first half of this code is taken directly from assignment 6.  I used 75% SAT math and ACT composite scores to predict selectivity of colleges, defining 20% admission or smaller as highly selective, 20-40% as selective, 40-60% as somewhat selective, and higher than 60% as not selective.  I expected from the summary statistics and the models that SAT and ACT scores are reasonably good predictors of college selectiveness.  I used accuracy score to find out how many colleges the model predicted correctly.  The SVC method predicted 87.5% correctly, but the Gaussian method, which the test harness had said was the most accurate, predicted everything correctly.  I would not expect that to happen in most cases, but the Gaussian does appear to be the best model in this circumstance, in terms of accuracy.